services:
  db:
    image: postgres:16.3
    container_name: postgres
    env_file:
      - .env.db
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - "app_files:/app/storage"

volumes:
  db_data:
  app_files:
