CREATE DATABASE FILE_STORAGE;

CREATE TABLE USERS(
    EMAIL VARCHAR(100) PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL
);

CREATE TABLE FILES(
    HASH VARCHAR(80) NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    SIZE INTEGER NOT NULL,
    DATE_OF_UPLOAD DATE NOT NULL,
    OWNER VARCHAR(100) NOT NULL,
    PRIMARY KEY (HASH, OWNER),
    CONSTRAINT USER_FK FOREIGN KEY(OWNER) REFERENCES USERS(EMAIL) ON DELETE CASCADE
);